"""
Column-index mappings for the 2024 asset-declaration form.

The form is generated by Oracle BI Publisher and every PDF follows the same
template, so column positions within each table are stable.  Sections are
identified first by column count, then — for ambiguous counts — by a keyword
found in the section title (row 2, col 0 of each table).

Table row structure (same on every page):
  row 0 : declaration serial header
  row 1 : "ΔΗΛΩΣΗ ΠΕΡΙΟΥΣΙΑΚΗΣ ΚΑΤΑΣΤΑΣΗΣ"
  row 2 : section title  ← used for disambiguation
  row 3 : column headers
  row 4+ : data rows

HEADER_SKIP_ROWS = 2 explicitly skips rows 0-1; rows 2-3 are filtered out
by per-section data-validation checks.

Sections and their column counts
─────────────────────────────────
 7 cols  → header (identity / personal info)
 9 cols  → income
11 cols  → safe_deposit_boxes   ("Μίσθωση θυρίδων σε τράπεζες...")
12 cols  → loans_detail         (specific loan certificates, dates dd/mm/yyyy)
13 cols  → deposits
18 cols  → vehicles | securities | loans_assets  (discriminate via title)
19 cols  → business_shares | real_estate_rights  (discriminate via title)
20 cols  → real_estate
"""

from __future__ import annotations

# ─── section name constants ─────────────────────────────────────────────────

HEADER = "header"
INCOME = "income"
VEHICLES = "vehicles"
SAFE_DEPOSIT_BOXES = "safe_deposit_boxes"
LOANS_DETAIL = "loans_detail"
DEPOSITS = "deposits"
LOANS_ASSETS = "loans_assets"
SECURITIES = "securities"
BUSINESS_SHARES = "business_shares"
REAL_ESTATE = "real_estate"
REAL_ESTATE_RIGHTS = "real_estate_rights"
UNKNOWN = "unknown"

# Map ncols → section name, or list of candidates when ambiguous.
# Ambiguous entries are resolved by _identify_section() using SECTION_TITLE_KEYWORDS.
NCOLS_TO_SECTION: dict[int, str | list[str]] = {
    7: HEADER,
    9: INCOME,
    11: SAFE_DEPOSIT_BOXES,
    12: LOANS_DETAIL,
    13: DEPOSITS,
    18: [VEHICLES, SECURITIES, LOANS_ASSETS],
    19: [BUSINESS_SHARES, REAL_ESTATE_RIGHTS],
    20: REAL_ESTATE,
}

# Greek keyword substrings (uppercase) found in row-2 section titles.
# Checked against the decoded (or raw) title; FIRST MATCH WINS.
# More-specific keywords must come before any prefix they contain
# (e.g. "ΣΥΜΜΕΤΟΧ" before "ΜΕΤΟΧ", "ΕΜΠΡΑΓΜΑΤ" before "ΑΚΙΝΗΤ").
SECTION_TITLE_KEYWORDS: dict[str, str] = {
    "ΣΥΜΜΕΤΟΧ":  BUSINESS_SHARES,    # "Συμμετοχές σε κάθε είδους επιχείρηση"
    "ΕΜΠΡΑΓΜΑΤ": REAL_ESTATE_RIGHTS, # "Ακίνητα και εμπράγματα δικαιώματα επί αυτών"
    "ΟΧΗΜΑΤ":    VEHICLES,           # "Κάθε χρήσης οχήματα, πλωτά και εναέρια μέσα"
    "ΜΕΤΟΧ":     SECURITIES,         # "Μετοχές ημεδαπών και αλλοδαπών εταιρειών..."
    "ΧΡΕΟΓΡΑΦ":  SECURITIES,         # alternative title fragment
    "ΑΞΙΟΓΡΑΦ":  SECURITIES,         # another alternative
    "ΔΑΝΕΙ":     LOANS_ASSETS,       # "Δάνεια που συνδέονται με αγορά ακινήτων"
    "ΘΥΡΙΔ":     SAFE_DEPOSIT_BOXES, # "Μίσθωση θυρίδων σε τράπεζες..."
}

# ─── column indices per section ─────────────────────────────────────────────
# Names ending in _raw → garbled Greek text (OCR target).
# Names without _raw  → numeric / date / Latin (extracts cleanly).

HEADER_COLS: dict[str, int] = {
    "declarant_surname_raw": 2,
    "declarant_given_raw": 2,
    "party_raw": 2,
    "employment_title_raw": 2,
}

INCOME_COLS: dict[str, int] = {
    "row_type_raw": 0,
    "category_raw": 2,
    "amount": 4,
    "currency_raw": 6,
    "notes_raw": 7,
}

# 18-col vehicle table ("Κάθε χρήσης οχήματα, πλωτά και εναέρια μέσα")
VEHICLE_COLS: dict[str, int] = {
    "row_type_raw": 0,
    "owner_type_raw": 1,
    "vehicle_info_raw": 3,    # ΕΙΔΟΣ ΟΧΗΜΑΤΟΣ (vehicle type: ΕΠΙΒΑΤΙΚΟ Ι.Χ., etc.)
    "cc_str": 4,              # ΚΥΒΙΣΜΟΣ / ΜΗΚΟΣ (engine cc or boat length)
    "ownership_pct_str": 7,   # ΙΔΙΟΚΤΗΣΙΑ % (numeric string, e.g. "100")
    "first_reg_year": 8,      # ΕΤΟΣ ΠΡΩΤΗΣ ΚΥΚΛΟΦΟΡΙΑΣ (first registration year)
    "acquisition_year": 9,    # ΕΤΟΣ ΚΤΗΣΗΣ (acquisition year)
    "purchase_price": 12,     # ΚΑΤΑΒΛΗΘΕΝ ΤΙΜΗΜΑ (€) paid price
}

DEPOSIT_COLS: dict[str, int] = {
    "row_type_raw": 0,
    "bank_raw": 1,
    "currency": 2,
    "account_type_raw": 3,
    "count": 6,
    "amount": 8,
    "notes_raw": 10,
}

REAL_ESTATE_COLS: dict[str, int] = {
    "index_raw": 0,                # "ΑΚΙΝΗΤΟ 1" — trailing digit used as row number
    "owner_type_raw": 1,           # ΚΑΤΟΧΟΣ (ΥΠΟΧΡΕΟΣ / ΣΥΖΥΓΟΣ)
    "status_raw": 2,               # ΚΑΤΑΣΤΑΣΗ Ή ΜΕΤΑΒΟΛΗ (ΑΠΟΚΤΗΣΗ ΣΕ ΤΡΕΧΟΥΣΑ/ΠΡΟΗΓΟΥΜΕΝΗ ΧΡΗΣΗ)
    "country_raw": 3,              # ΧΩΡΑ
    "region_raw": 4,               # ΠΕΡΙΦΕΡΕΙΑ
    "prefecture_raw": 5,           # ΝΟΜΟΣ
    # col 6 is a spacer (None) produced by pdfplumber for this merged-header table
    "municipality_raw": 7,         # ΔΗΜΟΣ
    "property_type_raw": 8,        # ΕΙΔΟΣ ΑΚΙΝΗΤΟΥ (ΜΟΝΟΚΑΤΟΙΚΙΑ, ΔΙΑΜΕΡΙΣΜΑ, etc.)
    "property_condition_raw": 9,   # ΚΑΤΑΣΤΑΣΗ ΑΚΙΝΗΤΟΥ
    "total_area_m2": 10,           # ΕΠΙΦΑΝΕΙΑ ΕΔΑΦΟΥΣ ΣΕ m2 (land/plot area)
    "floor_raw": 11,               # ΟΡΟΦΟΣ ΚΤΙΣΜΑΤΟΣ (ΥΠΟΓΕΙΟ, ΙΣΟΓΕΙΟ, 1ος, etc.)
    "covered_area_m2": 12,         # ΕΠΙΦΑΝΕΙΑ ΚΥΡΙΩΝ ΧΩΡΩΝ ΣΕ m2 (main floor area)
    "other_area_m2": 13,           # ΕΠΙΦΑΝΕΙΑ ΒΟΗΘΗΤΙΚΩΝ ΧΩΡΩΝ ΣΕ m2
    "build_year": 14,              # ΕΤΟΣ ΚΑΤΑΣΚΕΥΗΣ
    "acquisition_year": 15,        # ΕΤΟΣ ΚΤΗΣΗΣ
    "transfer_year": 16,           # ΕΤΟΣ ΜΕΤΑΒΙΒΑΣΗΣ
    "swimming_pool_m2": 17,        # ΤΕΤΡΑΓΩΝΙΚΑ ΜΕΤΡΑ ΠΙΣΙΝΑΣ
    "energy_production_kw": 18,    # ΙΣΧΥΣ ΜΟΝΑΔΑΣ ΠΑΡΑΓΩΓΗΣ ΕΝΕΡΓΕΙΑΣ
    # col 19 is a trailing spacer
}

BUSINESS_SHARE_COLS: dict[str, int] = {
    "owner_type_raw": 0,          # ΚΩΔ. ΥΠΟΧΡΕΟΥ (ΥΠΟΧΡΕΟΣ / ΣΥΖΥΓΟΣ)
    "participation_type_raw": 3,  # ΕΙΔΟΣ ΣΥΜΜΕΤΟΧΗΣ (ΑΤΟΜΙΚΗ ΕΠΙΧΕΙΡΗΣΗ, etc.)
    "business_type_raw": 4,       # ΕΙΔΟΣ ΕΠΙΧΕΙΡΗΣΗΣ (ΑΤΟΜΙΚΗ, ΑΕ, ΕΠΕ, etc.)
    "company_raw": 5,             # ΕΠΩΝΥΜΙΑ ΕΠΙΧΕΙΡΗΣΗΣ (company name)
    "country_raw": 6,             # ΧΩΡΑ
    "share_pct_prev": 8,          # % ΠΕΡΥΣΙΝΗΣ ΣΥΜΜΕΤΟΧΗΣ (previous year %)
    "share_pct": 9,               # % ΚΑΤΑ ΤΟ ΕΤΟΣ ΔΗΛΩΣΗΣ (current year %)
    "start_year": 10,             # ΕΤΟΣ ΕΝΑΡΞΗΣ/ΑΠΟΚΤΗΣΗΣ ΣΥΜΜΕΤΟΧΗΣ
    "initial_capital": 11,        # ΑΡΧΙΚΟ ΚΕΦΑΛΑΙΟ ΕΙΣΦΟΡΑΣ
    "book_value": 12,             # ΚΕΦΑΛΑΙΟ ΕΙΣΦΟΡΑΣ 31/12 (year-end capital)
    "sale_value": 13,             # ΑΞΙΑ ΠΩΛΗΣΗΣ
    "purchase_value": 14,         # ΑΞΙΑ ΑΓΟΡΑΣ
}

LOANS_ASSETS_COLS: dict[str, int] = {
    "row_type_raw": 0,
    "owner_type_raw": 1,
    "loan_type_raw": 3,
    "periodic_amount": 4,
    "ownership_pct": 7,
    "start_year": 8,
    "end_year": 9,
    "original_amount": 12,
    "remaining_amount": 13,
    "secured_type_raw": 14,
    "notes_raw": 15,
}

LOANS_DETAIL_COLS: dict[str, int] = {
    "row_type_raw": 0,
    "loan_type_raw": 2,
    "bank_raw": 3,
    "original_amount": 5,
    "currency_raw": 6,
    "outstanding": 7,
    "start_date": 8,
    "end_date": 9,
    "notes_raw": 10,
}

# 18-col securities table ("Μετοχές ημεδαπών και αλλοδαπών εταιρειών...")
SECURITIES_COLS: dict[str, int] = {
    "owner_type_raw": 0,       # ΕΠΕΝΔΥΤΗΣ (ΥΠΟΧΡΕΟΣ / ΣΥΖΥΓΟΣ)
    "instrument_type_raw": 3,  # ΕΙΔΟΣ ΧΡΕΟΓΡΑΦΟΥ (ΜΕΤΟΧΕΣ, ΕΠΕΝΔΥΤΙΚΑ ΑΣΦΑΛΙΣΤΙΚΑ ΣΥΜΒΟΛΑΙΑ, etc.)
    "title_raw": 4,            # ΤΙΤΛΟΣ ΧΡΕΟΓΡΑΦΟΥ
    "quantity_str": 5,         # ΠΟΣΟΤΗΤΑ
    "acquisition_value": 8,    # ΑΞΙΑ ΚΤΗΣΗΣ (€)
    "valuation": 9,            # ΑΠΟΤΙΜΗΣΗ (current market/book value)
    "sale_value": 10,          # ΑΞΙΑ ΠΩΛΗΣΗΣ/ΜΕΤΑΒΙΒΑΣΗΣ
}

# 11-col safe deposit boxes table ("Μίσθωση θυρίδων σε τράπεζες...")
SAFE_DEPOSIT_COLS: dict[str, int] = {
    "owner_raw": 0,            # ΔΙΚΑΙΟΥΧΟΣ (ΥΠΟΧΡΕΟΣ / ΣΥΖΥΓΟΣ)
    "institution_raw": 5,      # ΙΔΡΥΜΑ ΠΟΥ ΦΙΛΟΞΕΝΕΙ ΤΗ ΘΥΡΙΔΑ
    "country_raw": 7,          # ΧΩΡΑ
    "rental_year": 8,          # ΕΤΟΣ ΜΙΣΘΩΣΗΣ ΤΗΣ ΘΥΡΙΔΑΣ
    "notes_raw": 9,            # ΠΑΡΑΤΗΡΗΣΕΙΣ
}

# 19-col real estate rights/acquisitions table ("Ακίνητα και εμπράγματα δικαιώματα...")
REAL_ESTATE_RIGHTS_COLS: dict[str, int] = {
    "index_raw": 0,                     # "ΑΚΙΝΗΤΟ 1" — trailing digit used as row number
    "heir_name_raw": 1,                 # ΕΠΩΝΥΜΟ/ΟΝΟΜΑ ΚΛΗΡΟΝΟΜΟΥΜΕΝΟΥ (combined in PDF)
    "heir_capacity_raw": 2,             # ΙΔΙΟΤΗΤΑ ΚΛΗΡΟΝΟΜΟΥ
    "heir_acquisition_method_raw": 3,   # ΤΡΟΠΟΣ ΑΠΟΚΤΗΣΗΣ ΙΔΙΟΤΗΤΑΣ ΚΛΗΡΟΝΟΜΟΥ
    "rights_type_raw": 4,               # ΕΜΠΡΑΓΜΑΤΑ ΔΙΚΑΙΩΜΑΤΑ ("ΠΛΗΡΗΣ ΚΥΡΙΟΤΗΤΑ 100 %", etc.)
    "acquisition_method_raw": 5,        # ΤΡΟΠΟΙ ΚΤΗΣΗΣ (ΓΟΝΙΚΗ ΠΑΡΟΧΗ, ΑΓΟΡΑ, etc.)
    # col 6 is a spacer (None)
    "price_paid": 7,                    # ΣΥΝΟΛΙΚΟ ΚΑΤΑΒΛΗΘΕΝ ΤΙΜΗΜΑ ΣΕ ΕΥΡΩ (€)
    "money_sources_raw": 8,             # ΠΗΓΕΣ ΠΡΟΕΛΕΥΣΗΣ ΧΡΗΜΑΤΩΝ
    "acquisition_contract_number": 9,   # ΑΡΙΘΜΟΣ ΣΥΜΒΟΛΑΙΟΥ ΑΠΟΚΤΗΣΗΣ
    "objective_value": 10,              # ΑΝΤΙΚΕΙΜΕΝΙΚΗ ΑΞΙΑ ΣΥΜΒΟΛΑΙΟΥ ΑΠΟΚΤΗΣΗΣ
    # col 11 is a spacer (None)
    "currency": 12,                     # ΝΟΜΙΣΜΑ
    "received_price": 13,               # ΕΙΣΠΡΑΧΘΕΝ ΤΙΜΗΜΑ ΣΕ ΕΥΡΩ (€)
    "disposal_contract_number": 14,     # ΑΡΙΘΜΟΣ ΣΥΜΒΟΛΑΙΟΥ ΕΚΠΟΙΗΣΗΣ/ΜΕΤΑΒΟΛΗΣ
    "disposal_objective_value": 15,     # ΑΝΤΙΚΕΙΜΕΝΙΚΗ ΑΞΙΑ ΣΥΜΒΟΛΑΙΟΥ ΕΚΠΟΙΗΣΗΣ/ΜΕΤΑΒΟΛΗΣ
    "kaek": 16,                         # ΚΩΔ. ΑΡ. ΕΘΝΙΚΟΥ ΚΤΗΜΑΤΟΛΟΓΙΟΥ (Κ.Α.Ε.Κ.)
    "notes_raw": 17,                    # ΠΑΡΑΤΗΡΗΣΕΙΣ
    # col 18 is a trailing spacer
}

# ─── row-skip rules ──────────────────────────────────────────────────────────
# Always skip rows 0-1 (serial header + form title).
# Rows 2 (section title) and 3 (column headers) are filtered by per-section
# data-validation checks in each _parse_* function.
HEADER_SKIP_ROWS = 2
